# Generated by Django 3.1.4 on 2021-01-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('pattern', 'entity_type')},
        ),
    ]
