# Generated by Django 3.1.4 on 2021-01-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20210105_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='ignore_case',
            field=models.BooleanField(default=True),
        ),
    ]
