# Generated by Django 3.1.4 on 2021-01-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_entity_ignore_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='match_from_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='match_to_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='text_field_in_article',
            field=models.CharField(choices=[('T', 'Title'), ('D', 'Description')], default='T', max_length=1),
            preserve_default=False,
        ),
    ]
