# Generated by Django 3.1.1 on 2020-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('title', models.CharField(max_length=256)),
                ('link', models.URLField()),
                ('date_published', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('source', 'title')},
            },
        ),
    ]
