# Generated by Django 3.1.1 on 2020-09-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('source', 'title', 'link')},
        ),
    ]
