# Generated by Django 3.1.4 on 2021-01-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201231_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(max_length=128)),
                ('icon_url', models.URLField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='source_internal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.source'),
        ),
    ]
