# Generated by Django 3.1.4 on 2021-01-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210101_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
